src/cljs/wombats_web_client/components/navbar.cljs
src/cljs/wombats_web_client/db.cljs
src/cljs/wombats_web_client/handlers/games.cljs
src/cljs/wombats_web_client/handlers/root.cljs
src/cljs/wombats_web_client/handlers/ui.cljs
src/cljs/wombats_web_client/panels/home.cljs
src/cljs/wombats_web_client/panels/preview-game.cljs
src/cljs/wombats_web_client/routes.cljs
src/cljs/wombats_web_client/services/wombats.cljs
src/cljs/wombats_web_client/subs/games.cljs
src/cljs/wombats_web_client/subs/root.cljs
src/cljs/wombats_web_client/utils/collection.cljs
src/cljs/wombats_web_client/views.cljs

* add preview route
* updated active-panel to have meta data
* get game stats based on game-id

Get games and click game id to preview

---

project.clj
src/cljs/wombats_web_client/events/ui.cljs
src/cljs/wombats_web_client/events/user.cljs

@oconn @dehli 
effectful handler for loading relevant user data into the app-db after login
eventually i'll also request data for 'my games' in the bootstrap-user-data handler

adding bootstrapping for when user logs in

---

less/colors.less
less/forms.less
less/main.less
less/objects/button.less
less/panels/account.less
src/cljs/wombats_web_client/panels/account.cljs

doot doot log out button styles and container background color
@oconn @dehli
closes #40

log out button

---

src/cljs/wombats_web_client/events/user.cljs
src/cljs/wombats_web_client/panels/account.cljs

add auth token into db on sign in, sign out properly

---

src/cljs/wombats_web_client/events/games.cljs
src/cljs/wombats_web_client/events/user.cljs
src/cljs/wombats_web_client/routes.cljs
src/cljs/wombats_web_client/utils/auth.cljs

bootstrap data on user load

---

project.clj

* `lein clean`
* `lein cljsbuild once min`
* project built to resources/public

Build Min of JS

---

src/cljs/wombats_web_client/events/in_game.cljs
src/cljs/wombats_web_client/panels/game-play.cljs

@oconn 
clears app game stats/chat messages on panel unmount lifecycle method

Clear game state on component-will-unmount

---

less/colors.less
less/components/game-rankings.less
src/cljs/wombats_web_client/components/game_ranking.cljs

@oconn @dehli 
lookin sharp, no reordering on game score logic as of yet

Wombat status li is styled

---

src/cljs/wombats_web_client/constants/urls.cljs

Reverts willowtreeapps/wombats-web-client#107
sigh...never do this at the end of the day...
@oconn @dehli

Revert "New QA branch"

---

src/cljs/wombats_web_client/components/modals/join-wombat-modal.cljs

Fixes a bug where you can't select a wombat color when you try to join a game.

Bug fix for selecting wombat.

---

src/cljs/wombats_web_client/components/navbar.cljs
src/cljs/wombats_web_client/constants/urls.cljs
src/cljs/wombats_web_client/routes.cljs

Adds config to the navbar but does not include user roles to hide display/access to the url. Created new issue to track ( #116 )
Fixes navigation to show selected link based on `:active-panel`. There will be nothing selected for screens that aren't included in the `panel-router-map` such as the game play panel.

Fixed routing bug and added config to navbar

---

src/cljs/wombats_web_client/panels/games.cljs

Super quick bool update for `games.panel`
Game Card will likely have a nice refactor when I do issue #16

Joinable Card if open, Link if already joined

---

src/cljs/wombats_web_client/components/chat_box.cljs
src/cljs/wombats_web_client/panels/game-play.cljs

With this PR, if you're at the bottom of the chat box it will auto scroll you to the bottom of the messages. I also updated player count so it's not hard coded.

Auto Scroll Chat, Add player count

---

src/cljs/wombats_web_client/constants/games.cljs
src/cljs/wombats_web_client/events/games.cljs

**READY**
- Add query str for open games
- Add active-intermission to query string
- None

Query for Active Intermission Open Games

---

src/cljs/wombats_web_client/components/chat_box.cljs

Update formatter for chat time

Bugfix #108 Chat time

---

src/cljs/wombats_web_client/constants/games.cljs
src/cljs/wombats_web_client/events/games.cljs
src/cljs/wombats_web_client/utils/games.cljs

**READY**
- Move status query to function instead of `defonce`
- Move query builder to utils file
- Update `events/games.cljs` file to use query builder
- None

build status query with join and update file structure

---

less/components/game-rankings.less
src/cljs/wombats_web_client/components/game_ranking.cljs

**READY**
- Update wombat img size in game ranking
- None

resized wombat image on game play

---

src/cljs/wombats_web_client/components/modals/join-wombat-modal.cljs

**READY**
- Navigate to game if join successful
- None

Navigate to game you joined

---

src/cljs/wombats_web_client/components/cards/game.cljs
src/cljs/wombats_web_client/components/modals/join-wombat-modal.cljs
src/cljs/wombats_web_client/utils/games.cljs

**READY**
- Added utils to utils/games
- When error occurs on join modal, reload content  (this will show if a color has been chosen)
- Clear selected state until inline errors are implemented
- None

Update join modal if error occured, added utils

---

src/cljs/wombats_web_client/components/cards/game.cljs
src/cljs/wombats_web_client/constants/games.cljs

**READY**
- Created mapper for game type str with type as keyword
- None

Get string of game type

---

less/components/tabbed-container.less
less/panels/simulator.less
src/cljs/wombats_web_client/components/tabbed_container.cljs
src/cljs/wombats_web_client/panels/simulator.cljs

**READY**
- Addition of stack trace component
- None

add stacktrace component

---

less/objects/button.less
less/panels/simulator.less
resources/public/index.html
src/cljs/wombats_web_client/components/simulator/arena.cljs
src/cljs/wombats_web_client/components/simulator/code.cljs
src/cljs/wombats_web_client/components/simulator/configure.cljs
src/cljs/wombats_web_client/components/simulator/controls.cljs
src/cljs/wombats_web_client/components/simulator/output.cljs
src/cljs/wombats_web_client/components/simulator/stack_trace.cljs
src/cljs/wombats_web_client/db.cljs
src/cljs/wombats_web_client/events/simulator.cljs
src/cljs/wombats_web_client/panels/simulator.cljs
src/cljs/wombats_web_client/subs.cljs
src/cljs/wombats_web_client/utils/games.cljs

**READY**
- Support configuration
- Improve event listening & messaging
- Break into smaller components
- None

Refactor simulator code

---

less/panels/welcome.less
src/cljs/wombats_web_client/db.cljs
src/cljs/wombats_web_client/events/ui.cljs
src/cljs/wombats_web_client/events/user.cljs
src/cljs/wombats_web_client/panels/account.cljs
src/cljs/wombats_web_client/panels/games.cljs
src/cljs/wombats_web_client/panels/welcome.cljs
src/cljs/wombats_web_client/routes.cljs
src/cljs/wombats_web_client/subs.cljs
src/cljs/wombats_web_client/utils/auth.cljs
src/cljs/wombats_web_client/utils/local-storage.cljs
src/cljs/wombats_web_client/views.cljs

**READY**
- Hook landing page into application so that if you're not logged in you're redirected to this page
- nope
- background video

Landing Page Hooked into App

---

project.clj

**READY**
- Add `run-local` alias
- Rename `local-dev` to `run-dev`
- Yes, alias has changed to run the app.

Added local api configuration

---

src/cljs/wombats_web_client/routes.cljs

**READY**
- Check for logged in user, rather than just token
- none

Check for current-user loaded in db

---

src/cljs/wombats_web_client/components/modals/join_wombat_modal.cljs
src/cljs/wombats_web_client/core.cljs
src/cljs/wombats_web_client/db.cljs
src/cljs/wombats_web_client/events/bootstrap.cljs
src/cljs/wombats_web_client/events/in_game.cljs
src/cljs/wombats_web_client/events/spritesheet.cljs
src/cljs/wombats_web_client/events/ui.cljs
src/cljs/wombats_web_client/events/user.cljs
src/cljs/wombats_web_client/panels/games.cljs
src/cljs/wombats_web_client/routes.cljs
src/cljs/wombats_web_client/socket_dispatcher.cljs
src/cljs/wombats_web_client/subs.cljs
src/cljs/wombats_web_client/utils/bootstrap.cljs
src/cljs/wombats_web_client/utils/socket.cljs
src/cljs/wombats_web_client/views.cljs

**READY**
- Completely refactored bootstrapping.
- None

[Issue] Bootstrapping

---

less/main.less
src/cljs/wombats_web_client/views.cljs

**READY**
- Basic styling for loading
- None

basic styling for init page

---

externs.js
project.clj

**READY**
- Fixed `:advanced` optimization by adding an externs file.

Created externs for ace editor.

---

src/cljs/wombats_web_client/utils/socket.cljs

**READY**
- Add logging to failed parsing
- None

add socket logging

---

src/cljs/wombats_web_client/panels/game_play.cljs
src/cljs/wombats_web_client/subs.cljs
src/cljs/wombats_web_client/utils/socket.cljs

**READY**
- Remove some previously used code that we should have removed in the bootstrap refactor.
- None

Removed unneeded code.

---

src/cljs/wombats_web_client/panels/game_play.cljs

**READY**
- Make sure that the canvas doesn't grow larger than the height of the panel.
- None

[Feature] Responsive Canvas

---

src/cljs/wombats_web_client/components/game_ranking.cljs

**READY**
- Bug fix for health bar
- None

fix status for in game health

---

less/components/cards/game-card.less

Make entire game card clickable.

---

src/cljs/wombats_web_client/components/game_ranking.cljs
src/cljs/wombats_web_client/components/modals/join_wombat_modal.cljs
src/cljs/wombats_web_client/events/games.cljs

**READY**
- Don't fetch all games after joining game (so that stats aren't overridden).
- None

[Issue] Fix stats bug.

---

less/panels/simulator.less

Updated color for select

---

src/cljs/wombats_web_client/utils/games.cljs

**READY**
- Fixed sorting bug for filtering for my games in finished tab
- nah

Filter Finished games for my games

---

CHANGELOG.md
src/cljs/wombats_web_client/components/simulator/configure.cljs
src/cljs/wombats_web_client/components/simulator/controls.cljs
src/cljs/wombats_web_client/constants/urls.cljs
src/cljs/wombats_web_client/db.cljs
src/cljs/wombats_web_client/events/simulator.cljs
src/cljs/wombats_web_client/events/user.cljs
src/cljs/wombats_web_client/socket_dispatcher.cljs

**READY**
- Move simulator state transfer to xhr
- None
N/A

Bugfix Simulator Refactor

---

CHANGELOG.md
src/cljs/wombats_web_client/constants/local_storage.cljs
src/cljs/wombats_web_client/core.cljs
src/cljs/wombats_web_client/events/bootstrap.cljs
src/cljs/wombats_web_client/events/user.cljs
src/cljs/wombats_web_client/utils/bootstrap.cljs

**READY**
- Add ability for users to login with an access token
- None
N/A

Add redirect for access-keys

---

CHANGELOG.md
src/cljs/wombats_web_client/components/chat_box.cljs
src/cljs/wombats_web_client/components/game_ranking.cljs
src/cljs/wombats_web_client/components/modals/join_wombat_modal.cljs
src/cljs/wombats_web_client/components/modals/winner_modal.cljs
src/cljs/wombats_web_client/components/simulator/code.cljs
src/cljs/wombats_web_client/events/games.cljs
src/cljs/wombats_web_client/events/in_game.cljs
src/cljs/wombats_web_client/panels/game_play.cljs
src/cljs/wombats_web_client/panels/games.cljs
src/cljs/wombats_web_client/subs.cljs
src/cljs/wombats_web_client/utils/games.cljs

**READY/IN DEVELOPMENT/HOLD**
- Update app so it works with game state refactor.
- Made it so players are live sorted based on score.
- Hopefully none.

Game state refactor

---

CHANGELOG.md

Update CHANGELOG for QA

---

CHANGELOG.md

Updated CHANGLOG for release

---

CHANGELOG.md
less/components/cards/wombat-card.less

**READY**
- Hide delete button on Wombats card.
- You can no longer delete wombats from the card.

Hide delete button.

---

CHANGELOG.md
less/colors.less
less/components/modals/wombat-modal.less
less/components/text-input.less
src/cljs/wombats_web_client/components/modals/wombat_modal.cljs
src/cljs/wombats_web_client/components/select_input.cljs
src/cljs/wombats_web_client/events/user.cljs

**READY/IN DEVELOPMENT/HOLD**
- Add repositories with a dropdown rather than typing the name
- Cannot add a repository by typing the name

Dropdown for Choosing Repositories

---

CHANGELOG.md
less/panels/simulator.less
src/cljs/wombats_web_client/components/ace.cljs
src/cljs/wombats_web_client/components/simulator/code.cljs
src/cljs/wombats_web_client/components/simulator/output.cljs

@dehli I figured we'd do the clojure edn part in a different issue.
**IN DEVELOPMENT**

Feature/output formatting 

---

CHANGELOG.md
less/components/chat-box.less
less/panels/game-play.less
project.clj

Fixed issues with chat box in Safari

---

CHANGELOG.md
less/panels/games.less

**READY**
- Fixes issue from introduced by #285.

Fixed #339

---

project.clj

**READY**
- Added commas to attempt to fix the build issues by ensuring that npm install has finished

Added comma to attempt to fix postcss in an alternative way

---

CHANGELOG.md
src/cljs/wombats_web_client/components/simulator/controls.cljs
src/cljs/wombats_web_client/db.cljs
src/cljs/wombats_web_client/events/simulator.cljs
src/cljs/wombats_web_client/subs.cljs

**READY**
- Fixes #359 by creating a global reagent for the simulator play-pause state

Fixed #359

---

CHANGELOG.md
less/components/simulator/controls.less

**READY**
- Adds a click indicator for buttons to make it more clear that the simulator is actually working.
Very very hard to screenshot

Button Click Animation
